### ISSUE TITLE
Bing search for the demo link

### ISSUE THREAD

**Issue by meenaramcalfire** [pablomarin/GPT-Azure-Search-Engine#25]
Excellent architecture and description on the work flow / Read me. Thanks for providing details and quick resolutions I have a quick question. 
I am trying to do a bing search in the demo link provided.
I am getting the following information. Can you please let me know how to test the demo link for bing search
I am getting the following attached answers for bing search. Looks like it does Cognitive search alone on the internal data and hence does not  provide the answer from the internet
<img width="607" alt="Bing Search" src="https://github.com/pablomarin/GPT-Azure-Search-Engine/assets/131498679/b7369786-f7f2-4184-8aaa-be4d2f791b91">

**Comment by pablomarin** [comment]
I don't know what version of the repo you have fork, but on the latest version we published we don't do the "Hey Bing" anymore, but instead give instructions on the tool declaration about what tool to use when.  We have found that GPT-4 does a way better job at understanding the usage of tools. But since 99% of people doesn't have access yet to GPT-4, we simplified the tools declaration.

please sync your fork and see the changes in Notebook 7

**Comment by meenaramcalfire** [comment]
Thanks for the quick reply. I was testing on the demo link. I will try to test in Notebook 7

**Comment by pablomarin** [comment]
Demo link will behave like exactly as the last version of notebook 7
